services:
  api-demo:
    container_name: "api-demo"
    build: .
    ports:
      - "18080:18080"
    command: [ "-config-file", "/config/config.yaml" ]
    volumes:
      - ./config/config_docker.yaml:/config/config.yaml
